# Generated by Django 3.2 on 2022-11-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally_name', models.CharField(max_length=200)),
                ('ally_image', models.ImageField(upload_to='uploads/allies')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_text', models.CharField(max_length=200)),
                ('testimonial_author', models.CharField(max_length=200)),
            ],
        ),
    ]
