# Generated by Django 3.2 on 2022-12-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_ally_ally_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_author',
            field=models.CharField(max_length=200, verbose_name='Testimonial author'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.CharField(max_length=200, verbose_name='Testimonial text'),
        ),
    ]
